### PR TITLE
Ep 10039  new app seed

### PR DESCRIPTION
**Pull request by drewniu**
This is just an initial import to the depot. The seed isn't ready to be used but after the initial file replace the following diffs should be smaller.

### CODE REVIEW

**Comment by sulco** [comment]
I'm not sure if we need two whole set of configurations for these, we could limit the amount of duplication if we base it on one CLI project (e.g. https://github.com/Enplug/dashboard-directory-app/blob/redesign-ng4/.angular-cli.json - this still has some unnecessary duplication btw)

**Comment by drewniu** [comment]
I thought about it but am not convinced this is the right way. Generally these are 2 separate projects which are only stored in one repo. As such, I think they should have their own independent config files. 

It will be confusing if package.json files are different, sources are different but some of the config files are common.

Let's keep it separate for the sake of maintenance and clarity.

**Comment by jakubbuszynski** [comment]
Fully agree with Michal statement - one config for both projects are not
clear and definitely not very readable.
From the development perspective they are two separate projects - i think
we can split to two separate repos, but this is only my proposition.

wt., 18 lip 2017 o 10:42 użytkownik Michal Drewniak <
notifications@github.com> napisał:

**Comment by sulco** [comment]
> if package.json files are different
No, package.json would not be the same.

> these are 2 separate projects 
No, they are not. They work with the same structure of data, e.g. when I define the interfaces for the app's assets and themes they are used in both app and directory app. Changes of these critical structures involve changing both applications.

**Comment by drewniu** [comment]
The fact that 2 apps are using the same type of asset doesn't mean that they should be merged into one app. Each app will simply implement its own interfaces where necessary. We want to avoid specifying dependencies for app which doesn't use them and avoid sharing version numbers.

While it's true that some of the resources are common, it doesn't mean they need to be shared.

**Comment by sulco** [comment]
The separate versions number issue is a case that can be solved in this setup as well.

I really don't like the idea of this kind of copying stuff around - I believe this is more work and a bigger mental load than complicated(?) config. 

I gave the interface example because having them is really freeing in that you can just trust that the structure you code operates on is consistent throughout the system. Compared to that, in the duplication scenario we'd need to be more careful to keep them in sync. Now lets consider: which solution will be more prone to bugs?

We have a perfect case for using the available setup but instead we opt in to use more manual approach. 

I tried that and did experience the usefulness of it but if the idea still doesn't make sense for you I can agree to disagree ;)

**Comment by drewniu** [comment]
FYI: i'm considering the arguments ;-)

**Pull request merged**
